### ISSUE TITLE
Handling multiple events

### ISSUE THREAD

**Issue by randomd00d** [ZContent/icalendar#1]
How do we handle multiple events? The documentation is not clear on that.

By handling multiple events I mean this. Let's say that I have a PHP script which, after being triggered, performs a database query, which returns pairs of dates (from-to). How can I use your PHP library to create a calendar which includes all of these dates?

The dates are not reccuring. Instead they refer to unique events.

**Comment by cogliano** [comment]
Create two event objects, like this:

```
$icalobj = new ZCiCal();
$eventobj1 = new ZCiCalNode("VEVENT", $icalobj->curnode);
$eventobj1->addNode(new ZCiCalDataNode("SUMMARY:Event 1"));
...
$eventobj2 = new ZCiCalNode("VEVENT", $icalobj->curnode);
$eventobj2->addNode(new ZCiCalDataNode("SUMMARY:Event 2"));
...
```
