### ISSUE TITLE
Handling subnode

### ISSUE THREAD

**Issue by maxime-killinger** [ZContent/icalendar#8]
Can we create a subnode like this ?

BEGIN:VEVENT
BEGIN:VALARM
END:VALARM
END:VEVENT

I can't find anything about this.

Thank's

**Comment by cogliano** [comment]
Just add the VALARM to the VEVENT object like this:

require_once("../zapcallib.php");
$icalobj = new ZCiCal();
$eventobj = new ZCiCalNode("VEVENT", $icalobj->curnode);
$alarmobj = new ZCiCalNode("VALARM", $eventobj);
echo $icalobj->export();
